version: 0.2

env:
  variables:
    HADOOP_VERSION: "2.10.2"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install pyspark==3.1.2

  pre_build:
    commands:
      - wget https://archive.apache.org/dist/hadoop/common/hadoop-${HADOOP_VERSION}/hadoop-${HADOOP_VERSION}.tar.gz
      - tar -xzf hadoop-${HADOOP_VERSION}.tar.gz
      - export PATH=$PWD/hadoop-${HADOOP_VERSION}/bin:$PATH
      - export SPARK_DIST_CLASSPATH=$(hadoop classpath)
      
  build:
    commands:
      - cd src
      - python3 get_keys.py
      - python3 main.py

artifacts:
  files:
    - '**/*'