version: 0.2

phases:
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y python3-pip
      - python3 -m pip install pyspark==3.1.2
      - python3 -m pip install hadoop-aws==3.3.1
      
  build:
    commands:
      - cd src
      - python3 get_keys.py
      - python3 main.py

artifacts:
  files:
    - '**/*'